tuts/blog/urls.py
from django.urls import path,include
from .import views

urlpatterns =[
    path("",views.index,name="index"),
    path("<int:id>/details/",views.details,name="details")
]

tuts/company/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index"),
    path("<int:id>/details",views.details,name="details")

]

tuts/polls/urls.py
from django.urls import path
from .import views

app_name="polls"
urlpatterns=[
    path("",views.index,name="index"),
    path("<int:question_id>/",views.detail,name="detail"),
    path("<int:question_id>/results",views.results,name="results"),
    path("<int:question_id>/vote",views.vote,name="vote"),

]

tuts/todo/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add"),
    path("delete_item/<int:Todo_id>",views.delete_item,name="delete_item"),

]    

tuts/tuts/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    path('blog/',include('blog.urls')),
    path('todo/',include('todo.urls')),
    path('company/',include('company.urls')),
    path('utilities/',include('utilities.urls')),

]

tuts/utilities/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="index"),
    path("process",views.process,name="process")
]

tuts/blog/models.py
from django.db import models

# Create your models here.
class article(models.Model):
    reporter =models.CharField(max_length=50)
    article =models.TextField()

    def __str__(self):
        return self.reporter


tuts/company/models.py
from django.db import models

# Create your models here.
class company(models.Model):
    name =models.CharField(max_length=50)
    location = models.TextField()

    def __str__ (self):
        return self.name

tuts/polls/models.py
from django.db import models
class Question(models.Model):
    Question_text =models.CharField(max_length=200)
    pub_date =models.DateTimeField('date published')


class Choice(models.Model):
    Question =models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text =models.CharField(max_length=200)
    votes =models.IntegerField(default = 0)    

tuts/todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    date_added = models.DateTimeField('date published')
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text




tuts/utilities/models.py
from django.db import models

# Create your models here.

tuts/blog/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse
from .models import article

# Create your views here.
def index(request):
    post = article.objects.all()
    context ={"post" : post}
    return render(request,"blog/index.html",context)
    #return HttpResponse("Finally working.")
def details(request,id):
    post =get_object_or_404(article,pk=id)
    context={"a":post}
    return render(request,"blog/details.html",context)

tuts/company/views.py
from django.shortcuts import get_object_or_404,render
from .models import company
# Create your views here.

def index(request):
    call =company.objects.all()
    context ={"company":call}
    return render(request,"company/index.html",context)

def details(request,id):
    details =get_object_or_404(company,pk=id)
    context={"company":details}
    return render(request,"company/details.html",context)

tuts/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from . models import Question

def index(request):
    #latest = Question.objects.order_by("-pub_date")[:5]
    #template =loader.get_template('polls/index.html')
    #context={"latest" :latest }
    
    #return HttpResponse(template.render(context,request))

    #alternatively,without using HttpResponse you can bind the return
    latest =Question.objects.order_by('-pub_date')[:5]
    context ={"latest" : latest }
    return render(request,"polls/index.html",context)

def detail(request,question_id):
    #return HttpResponse("You're looking at  a question %s" % question_id)

    #using what is in the model to show details
    question =get_object_or_404(Question,pk=question_id)
    context ={"question":question} 
    return render(request,"polls/detail.html",context)

def results(request,question_id):
    response="This is an answer to the question %s"
    return HttpResponse % question_id
def vote(request,question_id):
    return HttpResponse("You're voting on question %s" % question_id)
    

tuts/todo/views.py
from django.shortcuts import render
from .models import Todo
from django.utils import timezone
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    getItems = Todo.objects.all().order_by('-date_added')
    context ={'item':getItems}
    return render(request,'todo/index.html',context)
def add(request):
    #if request.method == "POST":
    text = request.POST['text']
    date = timezone.now()

    add_item = Todo.objects.create(
        text =text,
        date_added = date
    )
    count = Todo.objects.all().count()    
    return HttpResponseRedirect('/todo') 

def delete_item(request,Todo_id):
    delete = Todo.objects.get(id = Todo_id).delete()
    return HttpResponseRedirect('/todo')        

tuts/utilities/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context ={}
    return render(request,'utilities/index.html',context)
def process(request):
    if request.method == 'POST':
        text = request.POST['text']
        process = text.upper()
    return HttpResponse(process)       

tuts/blog/templates/blog/details.html
{{ a.article }}

tuts/blog/templates/blog/index.html
{% for p in post  %}
    <h5>{{ p.reporter }}</h5>
    <a href="{{ p.id }}/details/">see more</a>
{% endfor %}

tuts/company/templates/company/details.html
{{ company.name }}
{{ company.location }}

tuts/company/templates/company/index.html
{% if company %}
    {% for c in company %}
        <h1>{{ c.company }}</h1>
        
        <p><a href="{% url 'company:details' %}/details">{{ c.location }}</a></p>
    {% endfor %}
{% else %}
    <p>There no available companies.</p>
{% endif %}

tuts/polls/templates/polls/detail.html
{{ question.Question_text }}
{{ question.pub_date }}

tuts/polls/templates/polls/index.html
{% if latest %}
<ul>
{% for question in latest %}
    <li><a href="{% url 'poll:detail' question_id %}">{{ question.Question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<li>There are no avaialble polls</li>
{% endif %}

tuts/todo/templates/Todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todolist</title>
    <link rel="stylesheet" href="{% static 'Todo/bootstrap.min.css' %}">
    <script src="{% static 'Todo/bootstrap.min.js'  %}"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="" class="navbar-brand">TODOLIST APP</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

tuts/todo/templates/Todo/index.html
{% extends 'todo/base.html' %}
{% block content %}
    <div class="container">
        <div class="row mt-4">
                <div class="col">
                    <h2>Add Item</h2>
                    <form action="add" method="POST">
                        {% csrf_token %}
                        <input type="text" class="form-control mb-2 mr-sm-2" name="text" placeholder="Enter Item.">
                        <button type="submit" class="btn btn-outline-success">Add Item</button>
                    </form>
                </div>
            </div>
        <div class="row mt-4">
            <div class="col mt-5">
                <ul class="list-group">
                    {% for i in item  %}
                    <li class="list-group-item">{{ i.text }}
                    <div class="float-right">
                        <form action="delete_item/{{ i.id }}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                        </form>
                    </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

 

tuts/utilities/templates/utilities/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text|Capitalise</title>
    <link rel="stylesheet" href="{% static 'utilities/bootstrap.min.css'  %}">
    <script src="{% static 'utilities/bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="" class="navbar-brand">UTILITIES APP</a>
    </nav>
    {% block content %}
    {% endblock content %}    
</body>
</html>


tuts/utilities/templates/utilities/index.html
{% extends 'utilities/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <form action="process" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="">Text Capitalise</label>
                <textarea name="text" id="" cols="300" rows="10" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">SAVE</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}